### ISSUE TITLE
401 erors

### ISSUE THREAD

**Issue by Phusebox** [schofieldn/zappi2pvoutput#3] opened 2022-03-03 13:22 UTC
Hi,

Does this still work? I can't seem to get it to do anything.

Log file:
Getting Zappi status information from https://sX.myenergi.net/cgi-jstatus-ZXXXXXXXX/ failed: The remote server returned an error: (401) Unauthorized.. Aborting ...

**Comment by schofieldn** [comment] 2022-03-05 15:23
Thanks Phusebox. This is most likely caused by a change to the MyEnergi API (https://myenergi.info/update-to-active-server-redirects-t2980.html). It's fixed in the latest commit, but it now requires Powershell 7 due to the use of a new argument when calling the invoke-webrequest cmdlet.

**Closed as completed by schofieldn** 2022-03-05 15:23 UTC

**Comment by Phusebox** [comment] 2022-03-07 09:09
Thanks for the update.
Edit: I wrongly assumed W11 had the latest version of Powershell. So updated Powershell and see this error:

Line |
 135 |          $ZappiStatus.zappi.gen = 0
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'gen' cannot be found on this object. Verify that the property exists and can be set.

**Comment by schofieldn** [comment] 2022-03-07 11:50
Hi Phusebox. The script hadn't been tested with a Zappi that wasn't configured to monitor power generation. I've uploaded a new version of the script for you that will hopefully cope with this scenario.

**Comment by Phusebox** [comment] 2022-03-07 12:16
Thanks. I get this in the log
7-3-2022 13:14 Uploading status data for 7-3-2022 13:14:22 failed: Consumed Power = -3189W, Temperature =  deg C, Supply Voltage = 233,9V: Bad request 400: Invalid power value [-3189].

But if I would add a fourth CT for my PV installation, that would improve the situation? Do you use four CT clamps?

**Comment by schofieldn** [comment] 2022-03-07 13:21
I'd need to understand more about your configuration. It it a single-phase or 3-phase supply? Do you have a Harvi? Is there any battery involved? How many CT clamps do you have and how are they configured on the Zappi?

The consumed power is the net value of the power being generated (zappi.gen) and the power being drawn from the grid (zappi.grd). While the zappi.grd value can be negative (ie if power is being exported to the grid), it is assumed that this is only possible if the power being generated exceeds what is being exported, so consumed power should always be a positive value.

In your case, you seem to have a negative consumed power value which seems to indicate you are exporting more than you are generating. Pvoutput.org will not allow the posting of negative power values and hence the error you are seeing.

Can you maybe provide a link to a screenshot of the MyEnergi app when you get the error?

**Comment by Phusebox** [comment] 2022-03-07 13:26
I have a 3 phase grid installation and a 1 phase pv installation. I just have a Zappi and a Hub. No battery. 3 CT clamps, all three are configured as Grid.

And yes, right now my solar panels are genatering around 3.5 kWh, and I am only consuming about .3 kWh. So the negative value is correct. Perhaps it is just not possible to do what I want without adding a fourth CT?

If I add the 4th one it would be able to distinguish the generation from the solar panels from the export and show the true consumption value?

**Comment by schofieldn** [comment] 2022-03-07 13:52
Yes I think so. To get an accurate consumption figure, you need to know how much you are generating, so a CT clamp (configured as Generation Only) is required on the output from the PV inverter / generation meter.

I have only a single-phase supply (3-phase domestic supply is not that common in the UK), so only 2 CT clamps - one on the grid supply and one on the generation.
